# Generated by Django 4.1 on 2022-08-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_com', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_reg', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='username',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('celular', models.IntegerField(default=0)),
                ('contraseña', models.CharField(max_length=16)),
                ('direccion', models.CharField(max_length=50)),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.comuna')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.region')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Depto',
            fields=[
                ('id_depto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.TextField(max_length=900)),
                ('disponible', models.BooleanField()),
                ('imagen', models.ImageField(null=True, upload_to='images/')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.comuna')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.region')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.comuna'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.region'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='catalogo.rol'),
        ),
    ]
