# Generated by Django 4.1 on 2022-09-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_comuna_region_rol_cliente_celular_cliente_contraseña_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Usuario',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
