# Generated by Django 4.1 on 2022-09-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_comuna_options_alter_depto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comuna',
            table='catalogo_comuna',
        ),
        migrations.AlterModelTable(
            name='depto',
            table='catalogo_depto',
        ),
        migrations.AlterModelTable(
            name='region',
            table='catalogo_region',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='catalogo_rol',
        ),
    ]
