# Generated by Django 4.1 on 2022-09-23 23:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_comuna_table_alter_depto_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_con', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guia_T',
            fields=[
                ('id_guia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('apellido', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_m', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_mo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.marca')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_t', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=50)),
                ('descripcion', models.TextField(max_length=1000)),
                ('precio', models.IntegerField(default=0)),
                ('conductor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.conductor')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=1000)),
                ('guia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.guia_t')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(default=0)),
                ('check_in', models.DateField(default=datetime.date.today)),
                ('check_out', models.DateField(default=datetime.date.today)),
                ('depto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.depto')),
                ('rut', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.usuario')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.tour')),
                ('transporte', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.transporte')),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='patente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.vehiculo'),
        ),
    ]
