# Generated by Django 4.1 on 2022-09-25 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_conductor_guia_t_marca_modelo_vehiculo_transporte_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={},
        ),
        migrations.AlterModelOptions(
            name='depto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
