# Generated by Django 4.1 on 2022-09-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_depto_habitacion_alter_comuna_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='depto',
        ),
        migrations.DeleteModel(
            name='Depto',
        ),
    ]
