# Generated by Django 4.1 on 2022-09-26 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_remove_reserva_depto_delete_depto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depto',
            fields=[
                ('id_depto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('habitaciones', models.IntegerField(default=1)),
                ('precio', models.IntegerField(default=0)),
                ('descripcion', models.TextField(max_length=900)),
                ('disponible', models.BooleanField()),
                ('imagen', models.ImageField(null=True, upload_to='images/')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.comuna')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.region')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='depto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.depto'),
        ),
    ]
