# Generated by Django 4.1.1 on 2022-10-16 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_imagendepto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='patente',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='guia',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='modelo',
        ),
    ]
