# Generated by Django 4.1.1 on 2022-10-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_remove_conductor_patente_remove_tour_guia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conductor',
        ),
        migrations.DeleteModel(
            name='Guia_T',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
