# Generated by Django 4.1.1 on 2022-10-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_delete_conductor_delete_guia_t_delete_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='nombre',
        ),
        migrations.AddField(
            model_name='tour',
            name='nombre_completo_guia',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='precio',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='conductor',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='marca',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='modelo',
            field=models.TextField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='patente',
            field=models.TextField(max_length=7, null=True),
        ),
    ]
