# Generated by Django 4.1 on 2022-10-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0015_remove_transporte_nombre_tour_nombre_completo_guia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='transporte',
        ),
    ]
