# Generated by Django 4.1 on 2022-10-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0016_remove_reserva_tour_remove_reserva_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
