# Generated by Django 4.1 on 2022-10-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0018_alter_reserva_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='Reservado', max_length=50, null=True),
        ),
    ]
