# Generated by Django 4.1 on 2022-10-23 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0020_alter_reserva_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_i', models.IntegerField(primary_key=True, serialize=False)),
                ('jabon', models.IntegerField(default=0, null=True)),
                ('toalla', models.IntegerField(default=0, null=True)),
                ('colchon', models.IntegerField(default=0, null=True)),
                ('sabanas', models.IntegerField(default=0, null=True)),
                ('id_depto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.depto')),
            ],
        ),
    ]
