# Generated by Django 4.1 on 2022-10-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0021_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='catalogo/static/img/'),
        ),
        migrations.AlterField(
            model_name='imagendepto',
            name='imagen',
            field=models.ImageField(upload_to='catalogo/static/img'),
        ),
    ]
