# Generated by Django 4.1 on 2022-10-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0022_alter_depto_imagen_alter_imagendepto_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenDepto',
        ),
    ]
