# Generated by Django 4.1 on 2022-10-24 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0023_delete_imagendepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='depto',
            name='imagen2',
            field=models.ImageField(null=True, upload_to='catalogo/static/img/'),
        ),
        migrations.AddField(
            model_name='depto',
            name='imagen3',
            field=models.ImageField(null=True, upload_to='catalogo/static/img/'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='depto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.depto'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='rut',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.usuario'),
        ),
    ]
