# Generated by Django 4.1 on 2022-11-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0024_depto_imagen2_depto_imagen3_alter_reserva_depto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='nombre_completo_guia',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='patente',
        ),
        migrations.AddField(
            model_name='reserva',
            name='nro_acompanante',
            field=models.IntegerField(default=0),
        ),
    ]
