# Generated by Django 4.1 on 2022-11-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0025_remove_tour_nombre_completo_guia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='nombre',
            field=models.CharField(default='Tour', max_length=15),
        ),
        migrations.AddField(
            model_name='transporte',
            name='nombre',
            field=models.CharField(default='Transporte', max_length=15),
        ),
    ]
