# Generated by Django 4.1 on 2022-11-11 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0026_tour_nombre_transporte_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.tour'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='transporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.transporte'),
        ),
    ]
