# Generated by Django 4.1 on 2022-11-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0027_reserva_tour_reserva_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
