# Generated by Django 4.1 on 2022-11-23 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0032_reserva_diferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id_checkout', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=900)),
                ('multa_infraestructura', models.IntegerField(default=0, null=True)),
                ('multa_inventario', models.IntegerField(default=0, null=True)),
                ('multa_otros', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('id_inv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.inventario')),
                ('id_res', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.reserva')),
            ],
        ),
    ]
