# Generated by Django 4.1 on 2022-11-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0033_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='depto',
            name='direccion',
            field=models.TextField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='id_tour',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='id_t',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
