from django.urls import path
from .views import *

urlpatterns= [
    path('', home, name="home"),
    path('depto/', Depto, name="depto"),
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('dashboard/', dashboard, name="dashboard"),
    path('dashboard/clientes', mantenedor_C, name="clientes"),
    path('dashboard/reservas', reservas, name="reserva"),
    path('dashboard/servicio_extra', mantenedor_SE, name="servicios"),
    path('dashboard/tour', tour, name="tour"),
    path('dashboard/guia', guia, name="guia"),
    path('dashboard/transporte', transporte, name="transporte"),
    path('dashboard/conductor', conductor, name="conductor"),
    path('dashboard/vehiculo', vehiculo, name="vehiculo"),
    path('dashboard/marca', marca, name="marca"),
    path('dashboard/modelo', modelo, name="modelo"),
    path('dashboard/listar_tour', listar_tour, name="listar_tour"),
    path('dashboard/modificar_tour/<id_tour>/', modificar_tour, name="modificar_tour"),
    path('dashboard/eliminar_tour/<id_tour>/', eliminar_tour, name="eliminar_tour"),
    path('dashboard/listar_guia', listar_guia, name="listar_guia"),
    path('dashboard/modificar_guia/<id_guia>/', modificar_guia, name="modificar_guia"),
    path('dashboard/eliminar_guia/<id_guia>/', eliminar_guia, name="eliminar_guia"),
    path('dashboard/listar_transporte', listar_transporte, name="listar_transporte"),
    path('dashboard/modificar_transporte/<id_t>/', modificar_transporte, name="modificar_transporte"),
    path('dashboard/eliminar_transporte/<id_t>/', eliminar_transporte, name="eliminar_transporte"),
    path('dashboard/listar_conductor', listar_conductor, name="listar_conductor"),
    path('dashboard/modificar_conductor/<id_con>/', modificar_conductor, name="modificar_conductor"),
    path('dashboard/eliminar_conductor/<id_con>/', eliminar_conductor, name="eliminar_conductor"),
    path('dashboard/listar_vehiculo', listar_vehiculo, name="listar_vehiculo"),
    path('dashboard/modificar_vehiculo/<patente>/', modificar_vehiculo, name="modificar_vehiculo"),
    path('dashboard/eliminar_vehiculo/<patente>/', eliminar_vehiculo, name="eliminar_vehiculo"),
    path('dashboard/listar_modelo', listar_modelo, name="listar_modelo"),
    path('dashboard/modificar_modelo/<id_mo>/', modificar_modelo, name="modificar_modelo"),
    path('dashboard/eliminar_modelo/<id_mo>/', eliminar_modelo, name="eliminar_modelo"),
    path('dashboard/listar_marca', listar_marca, name="listar_marca"),
    path('dashboard/modificar_marca/<id_m>/', modificar_marca, name="modificar_marca"),
    path('dashboard/eliminar_marca/<id_m>/', eliminar_marca, name="eliminar_marca"),
    path('listar_cliente/', listar_cliente, name="listar_cliente"),
    path('modificar_cliente/<rut>/', modificar_cliente, name="modificar_cliente"),
    path('eliminar_cliente/<rut>/', eliminar_cliente, name="eliminar_cliente"),
    #path('eliminar-depto/<id>/', eliminar_depto, name="eliminar_depto"),
    ]